"""Build WordPress HTML for CPG Benchmarks blog post."""

def make_table(headers, rows):
    # Every element gets explicit background AND color to prevent dark-on-dark
    h = ''.join(f'<th style="padding:14px 18px; text-align:left; font-weight:600; color:#ffffff; background:#1a1a1a;">{x}</th>' for x in headers)
    body = ''
    for i, row in enumerate(rows):
        row_bg = '#f9f9f9' if i % 2 == 1 else '#ffffff'
        cells = ''.join(f'<td style="color:#1a1a1a; background:{row_bg}; padding:12px 18px;{" font-weight:600;" if j==0 else ""}">{c}</td>' for j, c in enumerate(row))
        body += f'<tr style="border-bottom:1px solid #e0e0e0;">{cells}</tr>'
    return f'<div style="overflow-x:auto; margin:28px 0;"><table style="width:100%; border-collapse:collapse; font-size:0.95em; border-radius:12px; overflow:hidden; background:#ffffff; color:#1a1a1a; border:1px solid #e0e0e0;"><thead><tr style="background:#1a1a1a; color:#ffffff;">{h}</tr></thead><tbody>{body}</tbody></table></div>'

def callout(icon, title, color, bg, text):
    return f'<div style="background:{bg}; border-left:4px solid {color}; border-radius:0 8px 8px 0; padding:20px 24px; margin:28px 0;"><p style="font-weight:700; color:{color}; margin:0 0 8px 0;">{icon} {title}</p><p style="margin:0; line-height:1.7; color:#1a1a1a;">{text}</p></div>'

def step(num, title, desc):
    return f'<div style="display:flex; align-items:flex-start; margin:20px 0;"><div style="min-width:48px; height:48px; background:#ff6b35; color:#ffffff; border-radius:50%; display:flex; align-items:center; justify-content:center; font-weight:800; font-size:1.2em; margin-right:16px; flex-shrink:0;">{num}</div><div><p style="font-weight:700; margin:0 0 4px 0; font-size:1.05em; color:#1a1a1a;">{title}</p><p style="margin:0; color:#333333; line-height:1.7;">{desc}</p></div></div>'

def faq(question, answer):
    return f'<div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question" style="border-bottom:1px solid #e0e0e0; padding:20px 0;"><h3 itemprop="name" style="font-size:1.1em; margin:0 0 12px 0; color:#1a1a1a;">{question}</h3><div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><p itemprop="text" style="margin:0; line-height:1.7; color:#333333;">{answer}</p></div></div>'

parts = []

# KEY TAKEAWAYS
parts.append('<div style="background:linear-gradient(135deg, #fff5f0 0%, #fff 100%); border:2px solid #ff6b35; border-radius:12px; padding:28px 32px; margin:32px 0;"><p style="font-weight:800; font-size:1.15em; color:#ff6b35; margin:0 0 16px 0;">&#9889; Key Takeaways</p><ul style="margin:0; padding-left:20px; line-height:1.8;"><li><strong>DTC food brands spend $25-50 to acquire a customer</strong>, convert at 2.0-3.5% on Shopify, and lose 45-55% of subscribers within six months</li><li><strong>In-platform ROAS is inflated 30-50%</strong> vs Shopify-validated. If your agency only reports Meta ROAS, you don\'t know how ads are performing.</li><li><strong>Subscribers are worth 2.5x more</strong> than one-time buyers on a 12-month basis for food/bev DTC</li><li><strong>UGC gets 2-4x higher CTR and 30-50% lower CPA</strong> than polished studio content on Meta</li><li><strong>January is the best acquisition month</strong> with a 15-30% demand spike for health-focused food products</li></ul></div>')

# TOC
toc_items = [("acquisition", "Acquisition Benchmarks by Platform"), ("conversion", "Conversion Benchmarks"), ("retention", "Retention and Lifetime Value"), ("email-sms", "Email and SMS Benchmarks (Klaviyo)"), ("creative", "Creative Performance and Ad Fatigue"), ("seasonal", "Seasonal Patterns"), ("industry", "Industry Context"), ("framework", "The Replenishment Economics Framework"), ("mistakes", "4 Mistakes Better-for-You Brands Keep Making"), ("how-we-work", "How We Work With Better-for-You Brands"), ("faq", "Frequently Asked Questions")]
toc_li = ''.join(f'<li style="margin:8px 0;"><a href="#{id}" style="color:#ff6b35; text-decoration:none; font-weight:500;">{t}</a></li>' for id, t in toc_items)
parts.append(f'<div style="background:#f8f9fa; border-left:4px solid #ff6b35; padding:24px 28px; margin:32px 0; border-radius:0 8px 8px 0;"><p style="font-weight:700; font-size:1.1em; margin:0 0 12px 0; color:#1a1a1a;">In This Article</p><ul style="list-style:none; padding:0; margin:0;">{toc_li}</ul></div>')

# INTRO
parts.append('<p>Better-for-you CPG brands on Shopify spend $25-50 to acquire a customer, convert at 2.0-3.5%, and lose 45-55% of subscribers within six months. Those are the median numbers across DTC food and beverage ecommerce. If you sell clean label snacks, functional beverages, organic pantry staples, or supplements direct to consumer, this is the most comprehensive benchmark dataset available for your category, sourced from Triple Whale, Varos, Klaviyo, Littledata, Recharge, and our own portfolio of better-for-you brands we\'ve managed since 2017.</p><p>The problem is that most brands benchmark against general ecommerce data, which is useless when your AOV is $40 and you\'re competing for attention against fashion brands with $120 carts and 60% margins. Every number below is specific to food, beverage, and health/wellness DTC.</p>')

# STAT CARDS
cards = [("$25-50", "DTC Food CAC"), ("2.5x", "Median Meta ROAS"), ("45-55%", "Subscriber Churn (6mo)"), ("$2-6", "Abandoned Cart RPR"), ("94%", "Client Retention")]
card_html = ''.join(f'<div style="flex:1; min-width:170px; background:#fff; border:2px solid #ff6b35; border-radius:12px; padding:24px; text-align:center;"><div style="font-size:2.2em; font-weight:800; color:#ff6b35; line-height:1;">{v}</div><div style="font-size:0.85em; margin-top:8px; color:#666;">{l}</div></div>' for v, l in cards)
parts.append(f'<div style="display:flex; gap:16px; flex-wrap:wrap; margin:28px 0;">{card_html}</div>')

# ACQUISITION
parts.append(f'<h2 id="acquisition">Acquisition Benchmarks by Platform</h2><p>How much it costs to get a customer, broken down by where you\'re spending.</p>')
parts.append(make_table(['Platform', 'CPC', 'CPM', 'CTR', 'ROAS (In-Platform)', 'ROAS (Shopify-Validated)'], [['Meta (F&B)', '$0.42-0.70', '$8-14', '1.2-1.6%', '2.0-4.0x (median 2.5x)', '1.4-2.8x'], ['Meta (Health/Wellness)', '$0.80-1.50', '$10-18', '1.0-1.4%', '2.0-3.5x', '1.4-2.5x'], ['Google Search', '$1.50-2.50', 'N/A', '3.0-5.0%', '4.0-8.0x', '2.8-5.6x'], ['Google Shopping', '$0.50-0.90', 'N/A', '1.0-1.5%', '3.0-6.0x', '2.1-4.2x'], ['Performance Max', 'Varies', 'Varies', 'Varies', '3.0-5.0x', '2.1-3.5x'], ['TikTok', '$0.30-0.70', '$6-10', '0.8-1.3%', '1.5-2.5x', '1.0-1.8x']]))
parts.append(callout('&#127919;', 'Key Insight', '#7b1fa2', '#f3e5f5', '<strong>The Shopify-validated column is what matters.</strong> In-platform ROAS is inflated 30-50% because Meta and Google take credit for sales that were going to happen anyway (Triple Whale, 2023). If your agency only reports in-platform ROAS, you don\'t actually know how your ads are performing.'))
parts.append('<p><strong>CAC:LTV ratio:</strong> The healthy target is 1:3 or better (ProfitWell, 2023). Top-performing consumable brands hit 1:4 to 1:5 (Triple Whale, 2023). The median for DTC food is about 1:2.5, which means most food brands are spending too much to acquire or not retaining well enough.</p>')

# CONVERSION
parts.append(f'<h2 id="conversion">Conversion Benchmarks</h2><p>Where customers drop off between landing on your site and buying.</p>')
parts.append(make_table(['Metric', 'F&B Ecommerce', 'Health/Wellness', 'General Ecommerce'], [['Site conversion rate', '2.0-3.5% (median 2.8%)', '1.8-3.2%', '2.5-3.0%'], ['Mobile conversion', '1.5-2.5%', '1.3-2.2%', '1.8-2.5%'], ['Desktop conversion', '3.0-5.0%', '2.8-4.5%', '3.0-4.5%'], ['Add-to-cart rate', '8-12%', '7-10%', '7.5% avg'], ['Cart abandonment', '70-73%', '72-76%', '70% avg']]))
parts.append(callout('&#9888;&#65039;', 'Watch Out', '#f9a825', '#fff8e1', 'Unexpected shipping costs cause 48% of cart abandonments (Baymard, 2023). For perishable food brands, cold-chain shipping runs 25-40% of AOV (Shipbob, 2023). If you sell something that needs an ice pack, your checkout page needs to address shipping before people bail.'))
parts.append(make_table(['Subcategory', 'Median AOV'], [['Coffee (DTC)', '$30-50'], ['Snacks (DTC)', '$35-55'], ['Condiments/pantry (DTC)', '$35-50'], ['Beverages (DTC)', '$40-65'], ['Supplements (DTC)', '$50-80'], ['Meal kits', '$55-80'], ['General food DTC median', '$52']]))
parts.append('<p>If your AOV is below $45, paid acquisition math gets very tight. Most brands in that range need either a subscription model or a bundling strategy to make the unit economics work.</p>')

# RETENTION
parts.append(f'<h2 id="retention">Retention and Lifetime Value</h2><p>This is where better-for-you brands should have a structural advantage. Your product gets consumed. The customer needs more. The question is whether your marketing captures that reorder or lets it slip.</p><p><strong>Repeat purchase rate:</strong> 25-35% within 90 days for consumable DTC (Metrilo, 2023). Top-quartile consumable brands hit 40-55% (Repeat/Ordergroove, 2023). If your repeat rate is below 25%, your product or your post-purchase experience has a problem that no amount of ad spend will fix.</p>')
parts.append(make_table(['Subcategory', 'Days to Reorder', 'Implication'], [['Coffee', '25-35 days', 'Daily consumption, most predictable'], ['Supplements', '28-40 days', 'Dose-based, good for subscription'], ['Snacks', '30-45 days', 'Irregular, needs nudge'], ['Beverages', '30-50 days', 'Varies by format'], ['Meal kits', '7-14 days', 'Subscription-driven']]))
parts.append(callout('&#128161;', 'Pro Tip', '#1976d2', '#f0f7ff', 'These reorder windows are critical for your email and SMS timing. If your replenishment flow fires at day 30 but your customers reorder at day 45, you\'re early enough to be annoying but not late enough to catch them when they\'re actually running low.'))
parts.append(make_table(['Segment', '12-Month LTV'], [['DTC food/bev (median)', '$100-175'], ['DTC supplements', '$150-300'], ['Subscription food/bev', '$200-400']]))
parts.append('<p>Subscribers are worth 2.5x more on a 12-month basis for food/bev specifically (Ordergroove, 2023). A $40 one-time buyer is worth maybe $120 over 12 months. A $40 subscriber could be worth $300+.</p>')
parts.append(make_table(['Timeframe', '% Lost'], [['After month 1', '15-20%'], ['After month 3', '30-40%'], ['After month 6', '45-55%'], ['After month 12', '55-70%']]))
parts.append(make_table(['Subcategory', '6-Month Retention', 'Why'], [['Coffee', '50-60% (best in class)', 'Daily, predictable consumption'], ['Supplements', '45-55%', 'Dose-based, habitual'], ['Snacks/pantry', '35-45%', 'Less urgent reorder need'], ['Meal kits', '30-40% (worst)', 'Recipe fatigue, planning friction']]))

# EMAIL/SMS
parts.append(f'<h2 id="email-sms">Email and SMS Benchmarks (Klaviyo)</h2><p>Most better-for-you brands run on Klaviyo, so these benchmarks are Klaviyo-specific.</p>')
parts.append(make_table(['Flow', 'Open Rate', 'Click Rate', 'Revenue Per Recipient'], [['Welcome series', '45-55%', '4-8%', '$0.50-1.50'], ['Abandoned cart', '40-50%', '5-10%', '<strong>$2.00-6.00</strong>'], ['Browse abandonment', '35-45%', '2-4%', '$0.30-0.80'], ['Replenishment/reorder', '40-50%', '4-8%', '$1.00-3.00'], ['Post-purchase', '55-65%', '3-6%', '$0.20-0.50'], ['Win-back', '25-35%', '1-3%', '$0.10-0.30']]))
parts.append(callout('&#128161;', 'Pro Tip', '#1976d2', '#f0f7ff', 'Abandoned cart RPR of $2.00-6.00 is the single highest-RPR automation. If you don\'t have a cart abandonment flow running, you\'re leaving significant revenue on the table. Replenishment flows are where better-for-you brands have an edge over non-consumable categories.'))

# CREATIVE
parts.append(f'<h2 id="creative">Creative Performance and Ad Fatigue</h2><p>The single biggest operational challenge for food brands scaling on Meta.</p>')
parts.append(make_table(['Metric', 'Benchmark', 'Source'], [['Creative fatigue window', '2-4 weeks on Meta', 'Meta/Motion 2023'], ['UGC longevity', '3+ weeks (vs 1-2 for studio)', 'Meta/Motion 2023'], ['Frequency ceiling', '2.5-3.5 before decay', 'Smartly.io 2023'], ['UGC vs studio CTR', '2-4x higher for UGC', 'Aspire/Meta 2023'], ['UGC vs studio CPA', '30-50% lower for UGC', 'Aspire 2023'], ['Video vs static engagement', '20-40% higher for video', 'Meta/Smartly.io 2023'], ['Good hook rate (3-sec view)', '25-35% (excellent: 35%+)', 'Motion/VidMob 2023']]))
parts.append(make_table(['Monthly Meta Spend', 'Variants Needed'], [['$10K-30K', '10-20 new variants'], ['$30K-100K', '20-40+ variants'], ['$100K+', '40-80+ variants']]))
parts.append('<p>You can\'t run 4 ads and scale. At $50K/month in Meta spend you need 20-40 creative variants rotating monthly. That requires either a very efficient production process or a UGC pipeline. For food brands, the ROI on a $200 UGC video that runs for 3 weeks as an ad is dramatically better than a $5,000 studio shoot that fatigues in 10 days.</p>')

# SEASONAL
parts.append(f'<h2 id="seasonal">Seasonal Patterns for Better-for-You Brands</h2>')
parts.append(make_table(['Period', 'What Happens', 'Spend Implication'], [['January', '"New year, new me" drives 15-30% demand spike', 'Best acquisition month. Ramp in late December.'], ['February', '30-50% lift for chocolate and specialty food', 'Niche lift, gift sets'], ['May', 'Moderate lift for food gifting', 'Secondary opportunity'], ['June-July', 'Summer slump for most food DTC. Beverages see a lift.', 'Weakest period. Reduce spend or shift to beverages.'], ['September', 'Back-to-school + secondary health reset', 'Second-best month for acquisition'], ['Q4 (Nov-Dec)', '20-40% revenue lift for gift-able food/bev', 'Gift sets and bundles']]))

# INDUSTRY
parts.append('<h2 id="industry">Industry Context</h2><ul style="line-height:1.8;"><li>US natural and organic food: $63 billion at retail, growing 8-10% YoY (SPINS/NBJ, 2023)</li><li>"Better for you" snacks: $30 billion market (IRI/Circana, 2023)</li><li>Clean label food (global): $47 billion, projected $64 billion by 2027 (MarketsandMarkets, 2023)</li><li>Functional beverages (US): $25 billion (Grand View Research, 2023)</li><li>About 40-50% of all new CPG launches now carry a "better for you" claim (SPINS/Innova, 2023)</li></ul>')
parts.append(callout('&#9888;&#65039;', 'Plant-Based Exception', '#f9a825', '#fff8e1', 'After the 2020-2021 boom, US plant-based food sales have gone flat at about $8 billion, growing at roughly 1% (Good Food Institute, 2023). Brands in this subcategory need to be especially sharp on retention because the acquisition pool isn\'t expanding.'))

# FRAMEWORK
parts.append('<h2 id="framework">The Replenishment Economics Framework</h2><p>Here\'s how to figure out whether your paid media is actually working. We use this internally for every food brand we manage. We call it the Replenishment Economics Framework because it forces you to evaluate CAC against the natural reorder cycle, not against first-purchase ROAS.</p><div style="margin:28px 0;">')
parts.append(step(1, 'Find your product\'s natural replenishment window', 'Coffee might be 14-21 days. Hot sauce might be 45-60 days. Snack boxes might be 30 days. Use your time-to-second-purchase data from Shopify or Klaviyo, not a guess.'))
parts.append(step(2, 'Check your repeat purchase rate', 'The benchmark for consumable DTC is 25-35% (Metrilo, 2023). Below 25% means your product or post-purchase experience has a problem that more ad spend won\'t solve.'))
parts.append(step(3, 'Calculate your 90-day break-even CAC', 'Not first-purchase ROAS. If a customer spends $40 on order one and your repeat rate means they\'ll place 1.3 orders in 90 days, your 90-day value is about $52. At a 40% gross margin, you can afford a $20.80 CAC and break even in 90 days.'))
parts.append('</div>')
parts.append(callout('&#127919;', 'The Real Target', '#7b1fa2', '#f3e5f5', '<strong>That $20.80 is your real target.</strong> Not a platform ROAS number, not a first-order metric. Your actual break-even CAC over a realistic replenishment window. Brands that get this math right can scale aggressively because they know exactly what a customer is worth.'))

# MISTAKES
parts.append('<h2 id="mistakes">4 Mistakes Better-for-You Brands Keep Making</h2><p><strong>1. Optimizing for first purchase instead of replenishment.</strong> Most agencies optimize for purchase and report ROAS. For a food brand with a 30-day replenishment window, the business model depends on purchase #2, #3, and #4. If your agency isn\'t building retention into the media strategy from day one, they\'re solving the wrong problem.</p><p><strong>2. Running the same creative for too long.</strong> F&B creative fatigues in 2-4 weeks on Meta. Brands that set up 3-4 ads and let them run for a month see CPAs creep up 30-40%. You need a structured rotation cadence and a testing framework where each round feeds the next.</p><p><strong>3. Trusting in-platform ROAS.</strong> Meta takes credit for sales that were going to happen anyway, especially for consumable brands where repeat purchases inflate attribution. Pace against Shopify Gross Sales.</p><p><strong>4. Ignoring subscription retention after launch.</strong> Better-for-you brands lose 45-55% of subscribers within 6 months. The welcome flow gets built, the subscription launches, and then nothing. The brands that win are the ones investing as much in keeping subscribers as acquiring them.</p>')

# HOW WE WORK
parts.append('<h2 id="how-we-work">How We Work With Better-for-You Brands</h2><p>We\'ve spent years building a repeatable approach for this category: Meta and TikTok ads with creative strategies built for food, Klaviyo email and SMS flows mapped to replenishment cycles, Google Shopping and Performance Max with feed optimization, and retargeting segmented by buying stage. Everything paced against Shopify Gross Sales, reported weekly.</p><p><strong>Results:</strong></p><p>A DTC meat snack brand came to us to fix new customer acquisition. Within a year: 205% more new customers, CAC cut in half, 12x site traffic, ad budget scaled 6x while staying profitable.</p><p>A ros&eacute; wine brand wanted awareness through paid social. CTR up 80%, CPMs down 30% QoQ, engagement rates above 50%. They grew to #3 ros&eacute; in their category by end of 2023.</p><p>A baked goods brand needed organic visibility. Top-3 keyword rankings jumped, they beat competitors in categories like gluten-free cookies, and organic traffic drove real revenue gains in Q4.</p><p>94% of our clients stay year over year. The industry average is 75-84% (Predictable Profits, 2025).</p>')

# FAQ
parts.append('<h2 id="faq">Frequently Asked Questions</h2><div itemscope itemtype="https://schema.org/FAQPage">')
parts.append(faq('I sell food on Shopify. What should my Meta ROAS target actually be?', 'For food and beverage DTC on Shopify, target 2.0-2.5x holistic ROAS measured in Shopify Gross Sales, not Meta\'s dashboard. In-platform numbers are inflated 30-50% for consumable brands because Meta attributes repeat purchases it didn\'t cause. If you\'re hitting 2.0x Shopify-validated ROAS with a 90-day repeat rate above 30%, your acquisition is working. Below 1.5x Shopify-validated, you\'re probably losing money unless your subscription conversion rate is making up the difference on the back end.'))
parts.append(faq('How many creative variants do I actually need to scale Meta ads for a food brand?', 'At $10K-30K/month in Meta spend, you need 10-20 new creative variants per month. At $30K-100K, that jumps to 20-40+. Above $100K, you need 40-80+ (Motion/Common Thread Collective, 2023). UGC from nano-influencers ($100-300 per video) is the most cost-effective way to fill this pipeline. A $200 UGC video that runs for 3 weeks outperforms a $5,000 studio shoot that fatigues in 10 days.'))
parts.append(faq('My repeat purchase rate is below 25%. Should I be spending on ads at all?', 'A repeat rate below 25% for a consumable product means your product, packaging, or post-purchase experience has a problem that paid acquisition will only make more expensive. Before scaling ad spend, fix the retention fundamentals: make sure your replenishment email flow is timed to your actual reorder window, audit your unboxing experience, and check whether customers who do reorder are buying the same product or different SKUs. Once retention is at 25-30%+, paid acquisition economics start to work.'))
parts.append(faq('What\'s the best email and SMS strategy for a DTC food brand on Klaviyo?', 'Build these flows in priority order: abandoned cart first ($2.00-6.00 RPR), welcome series second ($0.50-1.50 RPR), replenishment/reorder third ($1.00-3.00 RPR, timed to your specific product\'s consumption cycle), and win-back fourth ($0.10-0.30 RPR, but converts 2-5% of lapsed customers). For campaigns, 3x per week with proper segmentation is the sweet spot. SMS click rates run 8-15% with $0.10-0.30 revenue per message.'))
parts.append(faq('How much should a better-for-you brand spend on marketing as a percentage of revenue?', 'Most DTC food and beverage brands allocate 15-25% of revenue to marketing, with paid media accounting for 60-70% of that budget and email/SMS accounting for 10-15%. At $2M annual revenue, that\'s roughly $25K-40K/month in total marketing spend. The Replenishment Economics Framework is more useful than a percentage target: calculate your 90-day break-even CAC based on your specific AOV, repeat rate, and margin, then work backward to determine how much you can profitably spend per channel.'))
parts.append('</div>')

# CTA
parts.append('<div style="background:#fff5f0; border:2px solid #ff6b35; border-radius:12px; padding:32px 36px; margin:40px 0; text-align:center;"><p style="font-size:1.3em; font-weight:700; margin:0 0 12px 0; color:#1a1a1a;">Want to talk about your brand?</p><p style="margin:0 0 20px 0; color:#555; line-height:1.7;">We work with better-for-you food, beverage, and supplement brands on Shopify. If any of these benchmarks look familiar, let\'s talk.</p><a href="https://jetfuel.agency/contact/" style="display:inline-block; background:#ff6b35; color:#fff; padding:14px 36px; border-radius:8px; text-decoration:none; font-weight:700; font-size:1.05em;">Book a Strategy Call</a></div>')

with open('scripts/cpg_blog_content.html', 'w', encoding='utf-8') as f:
    f.write('\n'.join(parts))
print(f'Written: {len(parts)} sections, {sum(len(p) for p in parts):,} chars')
